### ISSUE TITLE
Consent Sharing

### ISSUE THREAD

**Issue by VanessaAhmad** [adorsys/open-banking-gateway#495]
Consent Sharing between FinTech and User using DataSafe

- [x] [FE] Create user login form
- [x] [FE] Create user registration form
- [x] Create user login API
- [x] Create user registration API
- [x] Embed and configure Datasafe into the project. Datasafe should handle user registration calls by creating a new user. Also, Datasafe should support the case of a user having data and consent encryption secret keys.
- [x] Use encryption for Xs2a protocol (supplied by Facade) based on an encryption key that is stored in Datasafe (both FinTech secret key and User data encryption key should be usable).
- [x] Share the user's consent encryption (not data) key with FinTech when consent is granted. The shared consent should not be valid until call 4b is done (code2Token) that confirms on behalf of FinTech that consent belongs to the requested user. 
- [x] When new consent is created we need to store context needed to match it.
- [x] FinTech should be able to read users' consent encryption key and consent by using this key when PsuAuthData is provided

**Comment by valb3r** [comment]
Also, we need to implement and integrate
https://github.com/adorsys/datasafe/issues/188
https://github.com/adorsys/datasafe/issues/189
