### ISSUE TITLE
Release pipeline

### ISSUE THREAD

**Issue by valb3r** [adorsys/open-banking-gateway#907]
**Desired flow:**

![deploy-flow.png](https://images.zenhubusercontent.com/5dd3fc494ee0850001599dbb/23377921-fda2-4a4c-a436-20f144bbc250)

We need to establish a clear release pipeline. To achieve that we need 3 major steps (in order of implementation):
 - [x] Ensure that Docker images are being promoted to Docker-hub
 - [x] Do a 0.2.0 release with all current issues to be as current (0.19.1)
 - [ ] Migrate to Github actions and establish 1-month release cycle
 - [ ] Published Docker-images should be tagged as latest as well
 - [ ] Replace tags to latest in non-development docker-compose
 - [ ] Ensure excessive logging like https://travis-ci.com/github/adorsys/open-banking-gateway/jobs/371783232 is resolved

Eventually, the release will happen as artifact promotion from private artifact repository (Github packages, private docker repository) to public repositories. Artifact promotion will happen at the moment CI/CD receives tagged commit. The commit tag will become a release version.

![release-pipeline.png](https://images.zenhubusercontent.com/5dd3fc494ee0850001599dbb/bb468f28-3e60-488f-bb54-b4c261664211)

**Ensure that Docker images are being promoted to Docker-hub:**
 - [x] Update current release script to publish docker images from our private repository to DockerHub
 - [x] DevOps to install credentials for publishing to DockerHub 

**Do a 0.2.0 release with all current done issues to be as the current release until step 3 is done (Migration to Github actions)**
 - [x] Try to perform release with the current release script. Expected deliverables: Docker-containers with UI (FinTech, OpenBanking) and Backend (OpenBanking, FinTech, HBCI-Sandbox). JAR files with FinTech backend and OpenBanking backend (and JavaDoc) in public maven-central

**Migrate to Github actions and establish a 1-month release cycle:**
 - [ ] Migrate build pipeline to Github actions
 - [ ] Migrate smoke test pipeline to Github actions
 - [ ] Publish JARs to Github Packages (https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages) as intermediate build output for JAR (non-stable versions artifactory)
- [ ] Create tagged commit processing hook to perform release:

 -  Publish Docker images from the private repository 
 - JAR artifacts from Github Packages to maven central that are associated with the tagged commit

- [ ] DevOps To install necessary credentials into Github actions to publish images and promote JAR's

**Comment by valb3r** [comment]
Docker containers released at 0.19.1. Maven release failed, but do we really need it? Maybe it is better to do maven release with new pipeline
